# Numpy Introduction

In [2]:
# install by running this code
# pip install numpy

In [3]:
import numpy as np

# What is an array?

In [12]:
a = np.arange(6)
print(a)
a.shape

[0 1 2 3 4 5]


(6,)

In [9]:
a2 = a[np.newaxis, :]
print(a2)

[[0 1 2 3 4 5]]


In [10]:
a2.shape

(1, 6)

In [13]:
a2 = a[ : , np.newaxis]
print(a2)
a2.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [14]:
a3 = a2[np.newaxis, :]
print(a3)
a3.shape

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]]]


(1, 6, 1)

# Why do we have 1D, 2D or 3D arrays and where do we need them in Data Science?


# Creating Arrays with Numpy

In [22]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([(1, 2, 3, 4, 5, 6, 7), (4, 5, 6, 7, 8, 9, 10)])

In [43]:
a.dtype # data type of array elements

dtype('int32')

In [51]:
type(a) # type of array

numpy.ndarray

In [52]:
type(b)

numpy.ndarray

In [44]:
b.dtype

dtype('int32')

In [26]:
print(a)
a.shape

[1 2 3 4 5 6 7]


(7,)

In [25]:
print(b)
b.shape

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


(2, 7)

# Initialize arrays

In [34]:
zeros = np.zeros((2, 5)) # (rows, columns)
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
zeros.dtype

dtype('float64')

In [36]:
ones = np.ones((2, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
ones.dtype

dtype('float64')

In [48]:
full = np.full((2, 5), 7.5)
full

array([[7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5]])

In [49]:
full.dtype

dtype('float64')

In [40]:
identity = np.eye(5) # creating an identity matrix
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
identity.dtype

dtype('float64')

# Array attributes

In [53]:
a.shape # gives us the shape of array

(7,)

In [54]:
len(a) # gives us the length of elements in array

7

In [55]:
a.ndim

1

In [56]:
b.ndim # gives us the dimension of array

2

In [57]:
identity.ndim

2

In [58]:
a.size # gives us the number of elements in array

7

# basic operations

In [61]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [62]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [64]:
g = a - b # subtraction
g

array([[ 0,  0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3, -3]])

In [63]:
b - a

array([[0, 0, 0, 0, 0, 0, 0],
       [3, 3, 3, 3, 3, 3, 3]])

In [66]:
# addition
h = a + b
h

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [68]:
# another method
h1 = np.add(a, b)
h1

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [69]:
# multiplication
i = a * b
i

array([[ 1,  4,  9, 16, 25, 36, 49],
       [ 4, 10, 18, 28, 40, 54, 70]])

In [70]:
# division
j = a /b
j

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667, 0.7       ]])

In [73]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [72]:
# square of each element
k = a ** 2
k

array([ 1,  4,  9, 16, 25, 36, 49])