# Numpy (Part-2)

In [1]:
import numpy as np

In [8]:
empty = np.empty((2))
print(empty)
print(empty[1])

[1.07674443e+181 4.65499561e-118]
4.6549956096432615e-118


In [14]:
empty = np.empty((3, 4))
print(empty)
print("---------------")
print(empty[1])

[[9.23390247e-312 2.81617418e-322 0.00000000e+000 0.00000000e+000]
 [1.01855798e-312 4.47032019e-038 6.81159280e-091 5.93736837e-038]
 [2.32685252e-057 1.45195060e-051 6.48224659e+170 4.93432906e+257]]
---------------
[1.01855798e-312 4.47032019e-038 6.81159280e-091 5.93736837e-038]


In [20]:
x = np.arange(23)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [21]:
# array of even numbers from 0 to 22
even = np.arange(0, 23, 2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [23]:
# array of odd numbers from 0 to 23
odd = np.arange(1,24, 2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [30]:
# specific difference between numbers
diff = np.arange(0, 23, 3)
diff

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [33]:
# specific difference between numbers
diff = np.arange(0, 23, .515)
diff

array([ 0.   ,  0.515,  1.03 ,  1.545,  2.06 ,  2.575,  3.09 ,  3.605,
        4.12 ,  4.635,  5.15 ,  5.665,  6.18 ,  6.695,  7.21 ,  7.725,
        8.24 ,  8.755,  9.27 ,  9.785, 10.3  , 10.815, 11.33 , 11.845,
       12.36 , 12.875, 13.39 , 13.905, 14.42 , 14.935, 15.45 , 15.965,
       16.48 , 16.995, 17.51 , 18.025, 18.54 , 19.055, 19.57 , 20.085,
       20.6  , 21.115, 21.63 , 22.145, 22.66 ])

In [34]:
lin = np.linspace(0, 20, num=10)
lin

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [35]:
lin = np.linspace(0, 10, num=5)
lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
lin = np.linspace(0, 10, num=10)
lin

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [37]:
lin = np.linspace(0, -10, num=10)
lin

array([  0.        ,  -1.11111111,  -2.22222222,  -3.33333333,
        -4.44444444,  -5.55555556,  -6.66666667,  -7.77777778,
        -8.88888889, -10.        ])

In [44]:
lin = np.linspace(0, 10, num=15)
lin

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [45]:
lin.dtype

dtype('float64')

In [51]:
lin = np.linspace(0, 10, num=15, dtype=np.int64) # numbers are rounded off so they don't make sense
lin

array([ 0,  0,  1,  2,  2,  3,  4,  5,  5,  6,  7,  7,  8,  9, 10],
      dtype=int64)

In [54]:
# define the dtype of array
x  = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [56]:
# define the dtype of array
x  = np.ones(2, dtype=np.float64)
x

array([1., 1.])

In [60]:
# define the dtype of array
x  = np.arange(0, 22.6, 1.5, dtype=np.float64)
x

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5, 21. , 22.5])

# **Assignment:** What is the difference between int32, 64 or float 32, 64, 16... What do they mean? Why do we use one and not the other one?

The difference is the number of bits. A value expressed as a float32 is a floating-point number that occupies 32 bits of storage. Likewise, a float64 value is a floating-point number that occupies 64 bits of storage. We use them according to the range of numbers we have and if we want to save memory, we might use the data type with less storage.

In [61]:
# sorting an array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [63]:
arr = np.sort(arr)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

In [67]:
# concatenate these arrays
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Concatenate 2D Arrays

In [68]:
x = np.array([[1, 2], [3, 4]]) # 2x2 array
y = np.array([[5, 6]]) # 1x2 array

In [69]:
# concatenate 2D arrays
z = np.concatenate((x, y))
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [70]:
# concatenate 2D arrays on axis 0
z = np.concatenate((x, y), axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [78]:
# concatenate 2D arrays on axis 1
w = np.array([[5, 1], [7, 1]])
x = np.array([[1, 2], [3, 4]])
z1 = np.concatenate((w, x), axis=1)
z1

array([[5, 1, 1, 2],
       [7, 1, 3, 4]])

In [79]:
x.ndim

2

In [81]:
# create a 3D array
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                           
                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],
                            
                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]]])
array_example.ndim

3

In [82]:
len(array_example)

3

In [83]:
array_example.size

24

In [84]:
array_example.dtype

dtype('int32')

In [85]:
array_example.shape

(3, 2, 4)

In [87]:
# create a 3D array of size (3, 1, 4)
a  = np.array([[[0, 1, 2, 3]],
               [[4, 5, 6, 7]],
               [[0, 1, 2, 3]]])   
a.ndim

3

In [88]:
a.shape

(3, 1, 4)

In [90]:
# reshape the array
a = a.reshape(6, 2)
a.shape

(6, 2)

In [91]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 1],
       [2, 3]])

In [92]:
a.reshape(3, 2, 2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [95]:
a.reshape(3, 1, 4)

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]],

       [[0, 1, 2, 3]]])

In [96]:
# create a 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a.shape

(8,)

In [100]:
# convert that into 2D array
b = a[np.newaxis, :]
b.shape

(1, 8)

In [105]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [103]:
c = a[ : , np.newaxis]
c.shape

(8, 1)

In [104]:
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

# Indexing and slicing

In [106]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [107]:
a[2]

3

In [108]:
a[2: 5]

array([3, 4, 5])

In [109]:
a[-4:]

array([5, 6, 7, 8])

In [112]:
a[-4:-2]

array([5, 6])

In [113]:
a[1:]

array([2, 3, 4, 5, 6, 7, 8])

In [115]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [118]:
b[2]

array([ 9, 10, 11, 12])

In [119]:
b[1:, 1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [120]:
b[b < 5] # just like pandas filteration technique

array([1, 2, 3, 4])

In [121]:
b[b < 2]

array([1])

In [124]:
b[b >= 10]

array([10, 11, 12])

In [126]:
b[b <= 10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [128]:
b[b%2 == 0] # filter even numbers

array([ 2,  4,  6,  8, 10, 12])

In [130]:
b[b%2 == 1] # filter odd numbers

array([ 1,  3,  5,  7,  9, 11])

In [131]:
# use two conditions
b[(b > 2) & (b < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [132]:
# use three conditions and filter the arrays
b[(b > 2) & (b < 11) & (b%2 == 0)]

array([ 4,  6,  8, 10])

In [133]:
b[(b > 2) | (b < 11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])