# Numpy Indexing and Slicing

In [1]:
import numpy as np

In [3]:
# create an array
a = np.array([1, 2, 3, 4, 5, 6, 7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
a[0]

1

In [9]:
a[-2]

6

In [11]:
b = np.arange(0, 12, 2)
b

array([ 0,  2,  4,  6,  8, 10])

In [12]:
b[2]

4

In [14]:
c = b.reshape(2, 3)
c

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [15]:
c[0]

array([0, 2, 4])

In [16]:
a[0:1]

array([1])

In [18]:
a[1:5]

array([2, 3, 4, 5])

In [19]:
c[1]

array([ 6,  8, 10])

In [23]:
d = b.reshape(3, 2)
d

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [22]:
d[1]

array([4, 6])

In [30]:
d[(d < 5) & (d > 7)]

array([], dtype=int32)

In [31]:
d[(d < 5) | (d > 7)]

array([ 0,  2,  4,  8, 10])

## Enlist boolean operators or conditional operators

**Boolean Operators**: AND, OR, NOT

---
# Making an array from a data or another array

In [32]:
a = np.arange(0, 222, 5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [33]:
len(a)

45

In [34]:
array1 = a[40:45]
array1

array([200, 205, 210, 215, 220])

In [35]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([8, 9, 10, 11, 12, 13, 14])

In [36]:
c = np.vstack((a, b))
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [37]:
d = np.hstack((a, b))
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
d = d.reshape(2, 7)
d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

---
# Matrix or Matrices

In [41]:
# create a 2x3 matrix
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
# create a matrix of big dimension
b = np.arange(0, 100, 2).reshape(5, 10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [48]:
# create a matrix of big dimension
b = np.arange(0, 1000, 2).reshape(5, 100)
b

array([[  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
         26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
         52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
         78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
        104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
        130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
        156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
        182, 184, 186, 188, 190, 192, 194, 196, 198],
       [200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224,
        226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250,
        252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276,
        278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302,
        304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328,
        330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 35

In [49]:
# create a matrix
b = np.arange(0, 100, 2).reshape(5, 10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [59]:
# slicing a matrix of 3x2
c = b[0:3, 3:5]
c

array([[ 6,  8],
       [26, 28],
       [46, 48]])

In [60]:
b.max()

98

In [62]:
b.min()

0

In [63]:
b.sum()

2450

In [68]:
b.min(axis=0) # only for columns

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [69]:
b.min(axis=1) # only for rows

array([ 0, 20, 40, 60, 80])

In [70]:
b.max(axis=0) # only for columns

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [71]:
b.max(axis=1) # only for rows

array([18, 38, 58, 78, 98])

In [73]:
m = np.arange(0, 20, 2).reshape(5, 2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [76]:
m + np.array([20, 22]) # operation with each row

array([[20, 24],
       [24, 28],
       [28, 32],
       [32, 36],
       [36, 40]])

In [77]:
np.vstack((m, np.array([42, 44])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [42, 44]])

In [78]:
m * np.array([20, 22])

array([[  0,  44],
       [ 80, 132],
       [160, 220],
       [240, 308],
       [320, 396]])

In [79]:
m / np.array([20, 22])

array([[0.        , 0.09090909],
       [0.2       , 0.27272727],
       [0.4       , 0.45454545],
       [0.6       , 0.63636364],
       [0.8       , 0.81818182]])

In [80]:
m % np.array([20, 22])

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [81]:
m - np.array([20, 22])

array([[-20, -20],
       [-16, -16],
       [-12, -12],
       [ -8,  -8],
       [ -4,  -4]])

In [83]:
b = np.arange(0, 100, 2).reshape(5, 10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [84]:
np.flip(b)

array([[98, 96, 94, 92, 90, 88, 86, 84, 82, 80],
       [78, 76, 74, 72, 70, 68, 66, 64, 62, 60],
       [58, 56, 54, 52, 50, 48, 46, 44, 42, 40],
       [38, 36, 34, 32, 30, 28, 26, 24, 22, 20],
       [18, 16, 14, 12, 10,  8,  6,  4,  2,  0]])